### PR TITLE
Resolved MEW Contract Conflict Bug

### PR DESCRIPTION
**Pull request by Samyoul**
Resolution for bug #138

### CODE REVIEW

**Comment by Samyoul** [comment]
I accidentally merged from branch issue/139 rather than master, so this pull includes commits not yet in the master. Sorry about that.

I've basically played around a lot with this issue and the best solution to me seemed to test for the binding element that doesn't like being messed with and leaving it alone.

I've tried to make the logic as extensible as possible to allow other items in the future we may wish to exempt from the DOM manipulation.

**Comment by Samyoul** [comment]
All the changes unique to this issue are found in this commit : https://github.com/409H/EtherAddressLookup/pull/146/commits/43945084505fab95c9d9b4a9407060309810b77c

**Comment by 409H** [comment]
Will be testing this tonight

**Comment by 409H** [comment]
Sorry, I got a little busy over the last couple days. 
Marked this PR as a priority and will be done either tonight or tomorrow.

**Comment by Samyoul** [comment]
No probs, just whenever.

**Comment by 409H** [comment]
@Samyoul - can you commit to `manifest.json` and push the version to `1.9.1`.

**Comment by Samyoul** [comment]
@409H version updated

>Also, I can't replicate this anything since v1.9.0.
Yes, I noticed that too. This fix still addresses some weird behaviour with altering angular elements

With 1.9.0 I added a change that forced the regex to only be applied to textNodes, and moved new elements into `slots` avoiding unintended manipulation when looping over live collections of nodes/elements. Sometimes the regex got applied to element attribute elements and messed the HTML up.

I think the really bad problems were fixed with the introduction of using `slot` elements, previously chrome attempted to correct the misplaced elements so you couldn't actually see where the HTML was going wrong, but it affected the js behaviour.

**Pull request merged**
