### PR TITLE
Issue #17 - Levenshtein check

### PR DESCRIPTION
**Pull request by sogoiii**
I added the [levenshtein check](https://github.com/409H/EtherAddressLookup/issues/17) to catch similar words. I also created a passthrough specifically for myetherwallet. 

I did a small analysis on the blacklist and came up with the following results. The code for the analysis is [here](https://gist.github.com/sogoiii/aee03338132012245b888baddc8dff18)

```javascirpt
{
  "score": {
    "min": 1,
    "max": 27,
    "mean": 7.221316614420063,
    "median": 7,
    "std": 3.639774978064392
  }
}
```

If you look at the code, I have the limit set to `7 + 3.639774978064392`. This may be aggressive, and can always lowered.

### CODE REVIEW

**Comment by 409H** [comment]
Awesome! 
Will be playing around with this for an hour or so to get a feel of how strict it is - should be merged tonight if all goes well 👍

**Comment by 409H** [comment]
@sogoiii It seems a little aggressive (ie: blocking ethereum.org), will be playing around tweaking the numbers

Quick fiddle: https://repl.it/JZQ5

**Comment by sogoiii** [comment]
I'll play with it more today. and see how many sites it will block. It can definitely be lowered.

**Comment by 409H** [comment]
Ok, cool.

Here's a place I'm testing if you wanna use that; https://repl.it/JZQ5/1

**Comment by 409H** [comment]
Getting some good results with a base of 4, only 1 false positive: https://repl.it/JZQ5/3

**Comment by sogoiii** [comment]
Ok, I modified the code to remove the `std` stuff. That false positive you have is still ok because ledgerwallet.com resolves to www.ledgerwallet.com.

**Comment by 409H** [comment]
Ah okay cool.

I think we should make `b` become `myetherwalletcom` instead of `myetherwallet` due to some `.com` extensions, such as `.com.de`.

Doing `levenshtein("wwwledgerwalletcom", "myetherwalletcom")` with a `holisticLimit` of `7` is also giving a false positive - though I fear there may not be a perfect algorithm, which is totally fine - just need to pass that info to the user. Thoughts?

**Comment by sogoiii** [comment]
You are right, there will not be a perfect solution. We can only make a bulk of possible fishing sites invalid. Forcing them to be more and more obscure. For those cases, we can add them to the blacklist. And we can have a whitelist if we want to protect against special cases.

As of right now I think having only the host name `myetherwallet` is better because if we add the `com`, then words can become more similar. 

1. myetherwallet -------> wwwledgerwalletcom ---> score of 9
1. myetherwalletcom ---> wwwledgerwalletcom ---> score of 6

Lower means they are more similar.

**Comment by 409H** [comment]
Sorry for the late response, was sleeping.

I understand, I'll do some more test cases on repl, and come back to you - hoping to get this merged and released tonight.

**Comment by 409H** [comment]
Since it's very difficult to get a perfect algorithm with no false-positives, how about we tweak the numbers slightly to be harsh to block the majority, if not all, similar MEW domains, then create a whitelist for known false-positives. I'm happy to do the whitelist tonight and merge with this release. Thoughts?

**Comment by sogoiii** [comment]
I think a whitelist will be necessary. I think the following should happen.

1. Add Whitelist of known good urls 
2. we can keep a number like 6,7,8 as a similarly score. too high and other things become flagged too.
3. Possibly adjust messaging about adding to a whitelist?
4. Explore using a bloom filter for blacklist and whitelist checking

**Comment by 409H** [comment]
I like it! Good thoughts.

I'll create the whitelist functionality and get set up the message about adding to a whitelist. I think we can then experiment and put live tonight, then look at the bloom filter.

**Comment by 409H** [comment]
Putting the pull to `ft-levenshtein` - will then branch off that for the whitelist, then open the pull request to `master`.

**Comment by sogoiii** [comment]
alrighty

**Comment by 409H** [comment]
@sogoiii if you get a sec, please look over: https://github.com/409H/EtherAddressLookup/pull/27

**Pull request merged**
