### PR TITLE
add bllttriex.com new Google Ad phishing

### PR DESCRIPTION
**Pull request by jyap808**

### CODE REVIEW

**Comment by 409H** [comment]
Thanks!

**Comment by jyap808** [comment]
Thanks. Further evidence

https://twitter.com/sniko_/status/903344993460527105

**Comment by 409H** [comment]
That's me @jyap808  :D

**Comment by jyap808** [comment]
Ah lol!

**Comment by 409H** [comment]
Thanks for the report - blacklisted on MetaMask also. Place notes in the comments here: https://etherscamdb.info/scam/2166/

**Pull request merged**
