### PR TITLE
polyswarm.me

### PR DESCRIPTION
**Pull request by myhndl**

### CODE REVIEW

**Comment by myhndl** [comment]
Ugh, another one: `https://polyswarms.io`

Shall I file a second pull request? Sorry!

**Comment by myhndl** [comment]
And: `https://polyswamr.io/`

**Comment by 409H** [comment]
I'm in movile right now. Pls can you push them into this PR and I'll accept

**Comment by 409H** [comment]
polyswarms.io
https://urlscan.io/result/d1a4d8be-fa76-4889-af95-bb018fdb6327#summary
https://urlscan.io/result/a9c0bdec-3d03-4f8a-87e7-d8903ff1bbc9#summary

polyswarm.me
https://urlscan.io/result/6ef6230c-9206-44e2-83cb-cb0be4664f90#summary
https://urlscan.io/result/263f59b7-e58b-4d22-b7b4-b7305a975985#summary

polyswamr.io
https://urlscan.io/result/b7e6991c-f4f4-4a8b-9422-69002ad2d231#summary
address: 0xC7308d5A7220Dc021CCF417445cB28cBb8Fece66

**Pull request merged**
