### PR TITLE
Whitelist swarm.fund and blacklist scam site

### PR DESCRIPTION
**Pull request by wires**
Dear 409H,

This PR adds swarm.fund and a scam site.

### CODE REVIEW

**Comment by 409H** [comment]
I will blacklist `swarm.fund` due to it being phishing (confirmed below) - but can you add any information on on swarm.fund? I can't find anything to confirm it.

image

and many external links to swarm.fund

image

**Comment by wires** [comment]
Hi, no swarm.fund is the official domain, swarm.credit is the phishing site :+1:

**Comment by 409H** [comment]
Sorry, I mistyped - `swarm.credit` will be blacklisted

**Comment by wires** [comment]
thnks!

**Pull request closed without merging**
