### PR TITLE
Added Identicons / Ether Blockies

### LINKED ISSUE #91: Identicons
See the idea here: https://twitter.com/adm_chch/status/903216394644340736

> Could the browser generate one of those identicon graphics off the hash of the domain and show next to the URL...

### PR DESCRIPTION
**Pull request by Samyoul**
Resolves #91

This commit contains functionality for auto scaling blockie images to be inserted infront of any ethereum address

### CODE REVIEW

**Comment by Samyoul** [comment]
Cool. The source for the blockies is : https://github.com/ethereum/blockies/blob/master/blockies.min.js

Preview on my test file:

192 168 33 10 test html

On MEW the contract management page looks weird, every other line is affected. This is actually the same in version 1.9.0

myetherwallet com

**Comment by Samyoul** [comment]
What version do you want this PR setting to?

**Comment by 409H** [comment]
> What version do you want this PR setting to?

It's a feature instead of a bug fix, so `v1.10` would be good :+1:

**Comment by 409H** [comment]
> On MEW the contract management page looks weird, every other line is affected. This is actually the same in version 1.9.0

You were right, !146 actually seems to fix this! Nice job!

**Pull request merged**
